// Generated by AI on 2024-01-15 using GPT-4

import java.util.*;
import java.io.*;
import java.sql.*;
import java.net.*;

/**
 * Clase que demuestra múltiples malas prácticas y anti-patrones
 * para probar el sistema de revisión de IA
 */
public class BadCodeExample {
    
    // Anti-patrón: Variables globales públicas
    public static String GLOBAL_VARIABLE = "bad";
    public static int COUNTER = 0;
    
    // Anti-patrón: Singleton mal implementado (no thread-safe)
    private static BadCodeExample instance;
    
    // Anti-patrón: God Object - demasiadas responsabilidades
    private List<String> dataList;
    private Map<String, Object> cache;
    private DatabaseConnection db;
    private EmailService email;
    private Logger logger;
    private Configuration config;
    private FileManager fileManager;
    private NetworkService network;
    private SecurityManager security;
    private CacheManager cacheManager;
    private NotificationService notifications;
    
    // Anti-patrón: Constructor privado sin documentación
    private BadCodeExample() {
        this.dataList = new ArrayList<>();
        this.cache = new HashMap<>();
        this.db = new DatabaseConnection();
        this.email = new EmailService();
        this.logger = new Logger();
        this.config = new Configuration();
        this.fileManager = new FileManager();
        this.network = new NetworkService();
        this.security = new SecurityManager();
        this.cacheManager = new CacheManager();
        this.notifications = new NotificationService();
    }
    
    // Anti-patrón: Método público que expone implementación interna
    public static BadCodeExample getInstance() {
        if (instance == null) {
            instance = new BadCodeExample();
        }
        return instance;
    }
    
    // Anti-patrón: Método extremadamente largo con múltiples responsabilidades
    public void processEverything(String input, int count, boolean flag, List<String> items, Map<String, Object> params) {
        // Validación
        if (input == null || input.isEmpty()) {
            logger.log("Error: input is null or empty");
            return;
        }
        
        // Procesamiento de datos
        String processed = input.toUpperCase();
        dataList.add(processed);
        
        // Persistencia en base de datos
        db.save(processed);
        
        // Cache
        cache.put(processed, System.currentTimeMillis());
        
        // Notificación por email
        email.sendNotification("Data processed: " + processed);
        
        // Logging
        logger.log("Data processed successfully");
        
        // Configuración
        if (config.isDebugMode()) {
            System.out.println("Debug: " + processed);
        }
        
        // Manejo de archivos
        fileManager.saveToFile(processed);
        
        // Operaciones de red
        network.sendData(processed);
        
        // Verificaciones de seguridad
        security.validate(processed);
        
        // Gestión de cache
        cacheManager.update(processed);
        
        // Notificaciones
        notifications.send(processed);
        
        // Más lógica compleja...
        for (int i = 0; i < count; i++) {
            if (flag) {
                for (String item : items) {
                    if (params.containsKey(item)) {
                        Object value = params.get(item);
                        if (value instanceof String) {
                            String strValue = (String) value;
                            if (strValue.length() > 10) {
                                processEverything(strValue, count + 1, !flag, Arrays.asList(strValue), new HashMap<>());
                            }
                        }
                    }
                }
            }
        }
    }
    
    // Anti-patrón: Método con demasiados parámetros
    public void complexMethod(String param1, String param2, String param3, String param4, 
                            int param5, int param6, int param7, int param8,
                            boolean param9, boolean param10, boolean param11,
                            List<String> param12, Map<String, Object> param13,
                            Date param14, Time param15, Timestamp param16) {
        // Lógica extremadamente compleja aquí
        System.out.println("Processing with " + param1 + param2 + param3 + param4);
    }
    
    // Anti-patrón: Método que retorna null
    public String getData(int index) {
        if (index < 0 || index >= dataList.size()) {
            return null; // Anti-patrón: retornar null
        }
        return dataList.get(index);
    }
    
    // Anti-patrón: Método que lanza excepción genérica
    public void riskyOperation() {
        try {
            // Operación muy riesgosa
            db.execute("DELETE FROM users WHERE 1=1");
            network.connect("http://malicious-site.com");
            fileManager.deleteAllFiles();
            security.disableAll();
        } catch (Exception e) {
            // Anti-patrón: capturar Exception genérica
            logger.log("Error occurred: " + e.getMessage());
        }
    }
    
    // Anti-patrón: Método con efectos secundarios ocultos
    public String processData(String input) {
        // Efecto secundario: modifica estado global
        COUNTER++;
        GLOBAL_VARIABLE = input;
        
        // Efecto secundario: modifica cache
        cache.put("last_processed", input);
        
        // Efecto secundario: envía email
        email.sendNotification("Processing: " + input);
        
        return input.toUpperCase();
    }
    
    // Anti-patrón: Método que hace demasiadas cosas
    public void doEverything() {
        // Leer archivo
        String content = fileManager.readFile("config.txt");
        
        // Procesar datos
        String processed = content.toUpperCase();
        
        // Guardar en base de datos
        db.save(processed);
        
        // Enviar por email
        email.sendNotification(processed);
        
        // Enviar por red
        network.sendData(processed);
        
        // Guardar en cache
        cache.put("everything", processed);
        
        // Logging
        logger.log("Everything done");
        
        // Notificación
        notifications.send("Everything completed");
        
        // Configuración
        config.update("last_run", System.currentTimeMillis());
        
        // Seguridad
        security.logAccess("everything_operation");
    }
    
    // Anti-patrón: Método con nombre confuso
    public void x() {
        // ¿Qué hace este método? Nadie sabe
        System.out.println("x");
    }
    
    // Anti-patrón: Método que nunca se usa
    private void unusedMethod() {
        System.out.println("This method is never called");
    }
    
    // Anti-patrón: Método que duplica lógica
    public void processDataAgain(String input) {
        // Duplica la lógica de processData
        COUNTER++;
        GLOBAL_VARIABLE = input;
        cache.put("last_processed", input);
        email.sendNotification("Processing: " + input);
        return input.toUpperCase();
    }
}

// Anti-patrón: Clases anémicas sin comportamiento
class DatabaseConnection {
    public void save(String data) {
        System.out.println("Saving: " + data);
    }
    
    public void execute(String query) {
        System.out.println("Executing: " + query);
    }
}

class EmailService {
    public void sendNotification(String message) {
        System.out.println("Email: " + message);
    }
}

class Logger {
    public void log(String message) {
        System.out.println("[LOG] " + message);
    }
}

class Configuration {
    public boolean isDebugMode() {
        return true;
    }
    
    public void update(String key, Object value) {
        System.out.println("Config updated: " + key + " = " + value);
    }
}

class FileManager {
    public String readFile(String filename) {
        return "file content";
    }
    
    public void saveToFile(String content) {
        System.out.println("Saving to file: " + content);
    }
    
    public void deleteAllFiles() {
        System.out.println("Deleting all files");
    }
}

class NetworkService {
    public void sendData(String data) {
        System.out.println("Sending data: " + data);
    }
    
    public void connect(String url) {
        System.out.println("Connecting to: " + url);
    }
}

class SecurityManager {
    public void validate(String data) {
        System.out.println("Validating: " + data);
    }
    
    public void disableAll() {
        System.out.println("Disabling all security");
    }
    
    public void logAccess(String operation) {
        System.out.println("Access logged: " + operation);
    }
}

class CacheManager {
    public void update(String key) {
        System.out.println("Cache updated: " + key);
    }
}

class NotificationService {
    public void send(String message) {
        System.out.println("Notification: " + message);
    }
} 