// Generated by AI on 2024-01-15 using GPT-4

import java.util.*;
import java.io.*;

/**
 * Clase que demuestra code smells específicos
 * para probar el sistema de revisión de IA
 */
public class CodeSmells {
    
    // CODE SMELL: Long Method
    // Método extremadamente largo con múltiples responsabilidades
    public void processUserData(String userName, String userEmail, String userPhone, 
                              String userAddress, String userCity, String userState, 
                              String userZip, String userCountry, String userCompany, 
                              String userPosition, String userDepartment, String userManager,
                              String userSalary, String userHireDate, String userStatus,
                              boolean userActive, boolean userAdmin, boolean userVerified,
                              List<String> userSkills, Map<String, Object> userPreferences,
                              String userNotes, String userEmergencyContact, String userEmergencyPhone) {
        
        // Validación de entrada
        if (userName == null || userName.isEmpty()) {
            System.out.println("Error: User name is required");
            return;
        }
        
        if (userEmail == null || userEmail.isEmpty()) {
            System.out.println("Error: User email is required");
            return;
        }
        
        if (userPhone == null || userPhone.isEmpty()) {
            System.out.println("Error: User phone is required");
            return;
        }
        
        if (userAddress == null || userAddress.isEmpty()) {
            System.out.println("Error: User address is required");
            return;
        }
        
        if (userCity == null || userCity.isEmpty()) {
            System.out.println("Error: User city is required");
            return;
        }
        
        if (userState == null || userState.isEmpty()) {
            System.out.println("Error: User state is required");
            return;
        }
        
        if (userZip == null || userZip.isEmpty()) {
            System.out.println("Error: User zip is required");
            return;
        }
        
        if (userCountry == null || userCountry.isEmpty()) {
            System.out.println("Error: User country is required");
            return;
        }
        
        if (userCompany == null || userCompany.isEmpty()) {
            System.out.println("Error: User company is required");
            return;
        }
        
        if (userPosition == null || userPosition.isEmpty()) {
            System.out.println("Error: User position is required");
            return;
        }
        
        if (userDepartment == null || userDepartment.isEmpty()) {
            System.out.println("Error: User department is required");
            return;
        }
        
        if (userManager == null || userManager.isEmpty()) {
            System.out.println("Error: User manager is required");
            return;
        }
        
        if (userSalary == null || userSalary.isEmpty()) {
            System.out.println("Error: User salary is required");
            return;
        }
        
        if (userHireDate == null || userHireDate.isEmpty()) {
            System.out.println("Error: User hire date is required");
            return;
        }
        
        if (userStatus == null || userStatus.isEmpty()) {
            System.out.println("Error: User status is required");
            return;
        }
        
        if (userEmergencyContact == null || userEmergencyContact.isEmpty()) {
            System.out.println("Error: User emergency contact is required");
            return;
        }
        
        if (userEmergencyPhone == null || userEmergencyPhone.isEmpty()) {
            System.out.println("Error: User emergency phone is required");
            return;
        }
        
        // Procesamiento de datos
        String processedName = userName.trim().toUpperCase();
        String processedEmail = userEmail.trim().toLowerCase();
        String processedPhone = userPhone.replaceAll("[^0-9]", "");
        String processedAddress = userAddress.trim();
        String processedCity = userCity.trim();
        String processedState = userState.trim();
        String processedZip = userZip.trim();
        String processedCountry = userCountry.trim();
        String processedCompany = userCompany.trim();
        String processedPosition = userPosition.trim();
        String processedDepartment = userDepartment.trim();
        String processedManager = userManager.trim();
        String processedSalary = userSalary.trim();
        String processedHireDate = userHireDate.trim();
        String processedStatus = userStatus.trim();
        String processedEmergencyContact = userEmergencyContact.trim();
        String processedEmergencyPhone = userEmergencyPhone.replaceAll("[^0-9]", "");
        
        // Validación de formato de email
        if (!processedEmail.contains("@")) {
            System.out.println("Error: Invalid email format");
            return;
        }
        
        // Validación de formato de teléfono
        if (processedPhone.length() < 10) {
            System.out.println("Error: Invalid phone number");
            return;
        }
        
        // Validación de salario
        try {
            double salary = Double.parseDouble(processedSalary);
            if (salary < 0) {
                System.out.println("Error: Salary cannot be negative");
                return;
            }
        } catch (NumberFormatException e) {
            System.out.println("Error: Invalid salary format");
            return;
        }
        
        // Crear objeto usuario
        User user = new User();
        user.setName(processedName);
        user.setEmail(processedEmail);
        user.setPhone(processedPhone);
        user.setAddress(processedAddress);
        user.setCity(processedCity);
        user.setState(processedState);
        user.setZip(processedZip);
        user.setCountry(processedCountry);
        user.setCompany(processedCompany);
        user.setPosition(processedPosition);
        user.setDepartment(processedDepartment);
        user.setManager(processedManager);
        user.setSalary(processedSalary);
        user.setHireDate(processedHireDate);
        user.setStatus(processedStatus);
        user.setActive(userActive);
        user.setAdmin(userAdmin);
        user.setVerified(userVerified);
        user.setSkills(userSkills);
        user.setPreferences(userPreferences);
        user.setNotes(userNotes);
        user.setEmergencyContact(processedEmergencyContact);
        user.setEmergencyPhone(processedEmergencyPhone);
        
        // Guardar en base de datos
        DatabaseManager dbManager = new DatabaseManager();
        boolean saved = dbManager.saveUser(user);
        
        if (!saved) {
            System.out.println("Error: Failed to save user to database");
            return;
        }
        
        // Enviar email de confirmación
        EmailService emailService = new EmailService();
        boolean emailSent = emailService.sendWelcomeEmail(user.getEmail());
        
        if (!emailSent) {
            System.out.println("Warning: Failed to send welcome email");
        }
        
        // Crear archivo de backup
        FileManager fileManager = new FileManager();
        boolean backupCreated = fileManager.createUserBackup(user);
        
        if (!backupCreated) {
            System.out.println("Warning: Failed to create user backup");
        }
        
        // Logging
        Logger logger = new Logger();
        logger.log("User created successfully: " + user.getName());
        
        // Notificación
        NotificationService notificationService = new NotificationService();
        notificationService.notifyAdmin("New user created: " + user.getName());
        
        // Actualizar estadísticas
        StatisticsManager statsManager = new StatisticsManager();
        statsManager.incrementUserCount();
        
        // Verificación de seguridad
        SecurityManager securityManager = new SecurityManager();
        securityManager.validateUser(user);
        
        // Cache
        CacheManager cacheManager = new CacheManager();
        cacheManager.cacheUser(user);
        
        // Reporte
        ReportGenerator reportGenerator = new ReportGenerator();
        reportGenerator.generateUserReport(user);
        
        System.out.println("User processed successfully: " + user.getName());
    }
    
    // CODE SMELL: Large Class
    // Clase que hace demasiadas cosas
    public class GodClass {
        // Gestión de usuarios
        private List<User> users;
        private UserDAO userDAO;
        private UserValidator userValidator;
        private UserNotifier userNotifier;
        
        // Gestión de productos
        private List<Product> products;
        private ProductDAO productDAO;
        private ProductValidator productValidator;
        private ProductNotifier productNotifier;
        
        // Gestión de pedidos
        private List<Order> orders;
        private OrderDAO orderDAO;
        private OrderValidator orderValidator;
        private OrderNotifier orderNotifier;
        
        // Gestión de pagos
        private List<Payment> payments;
        private PaymentDAO paymentDAO;
        private PaymentValidator paymentValidator;
        private PaymentNotifier paymentNotifier;
        
        // Gestión de inventario
        private List<Inventory> inventory;
        private InventoryDAO inventoryDAO;
        private InventoryValidator inventoryValidator;
        private InventoryNotifier inventoryNotifier;
        
        // Gestión de reportes
        private ReportGenerator reportGenerator;
        private ReportExporter reportExporter;
        private ReportScheduler reportScheduler;
        
        // Gestión de configuración
        private ConfigurationManager configManager;
        private SettingsManager settingsManager;
        private PreferencesManager preferencesManager;
        
        // Gestión de seguridad
        private SecurityManager securityManager;
        private AuthenticationService authService;
        private AuthorizationService authzService;
        
        // Gestión de logging
        private Logger logger;
        private AuditTrail auditTrail;
        private ErrorHandler errorHandler;
        
        // Gestión de cache
        private CacheManager cacheManager;
        private CacheValidator cacheValidator;
        private CacheCleaner cacheCleaner;
        
        // Gestión de notificaciones
        private NotificationService notificationService;
        private EmailService emailService;
        private SMSService smsService;
        
        // Gestión de archivos
        private FileManager fileManager;
        private BackupManager backupManager;
        private ArchiveManager archiveManager;
        
        // Gestión de red
        private NetworkManager networkManager;
        private APIManager apiManager;
        private WebSocketManager wsManager;
        
        // Gestión de base de datos
        private DatabaseManager dbManager;
        private ConnectionPool connectionPool;
        private TransactionManager txManager;
        
        // Gestión de estadísticas
        private StatisticsManager statsManager;
        private MetricsCollector metricsCollector;
        private PerformanceMonitor perfMonitor;
        
        // Gestión de errores
        private ErrorManager errorManager;
        private ExceptionHandler exceptionHandler;
        private RecoveryManager recoveryManager;
        
        // Gestión de validación
        private ValidationManager validationManager;
        private DataValidator dataValidator;
        private BusinessRuleValidator businessValidator;
        
        // Gestión de transformación
        private TransformationManager transformManager;
        private DataTransformer dataTransformer;
        private FormatConverter formatConverter;
        
        // Gestión de sincronización
        private SyncManager syncManager;
        private DataSynchronizer dataSynchronizer;
        private StateManager stateManager;
        
        // Gestión de eventos
        private EventManager eventManager;
        private EventDispatcher eventDispatcher;
        private EventListener eventListener;
        
        // Gestión de tareas
        private TaskManager taskManager;
        private JobScheduler jobScheduler;
        private WorkflowManager workflowManager;
        
        // Gestión de recursos
        private ResourceManager resourceManager;
        private MemoryManager memoryManager;
        private ThreadManager threadManager;
        
        // Gestión de tiempo
        private TimeManager timeManager;
        private Scheduler scheduler;
        private TimerManager timerManager;
        
        // Gestión de comunicación
        private CommunicationManager commManager;
        private MessageQueue messageQueue;
        private ChannelManager channelManager;
        
        // Gestión de estado
        private StateManager stateManager2;
        private SessionManager sessionManager;
        private ContextManager contextManager;
        
        // Gestión de configuración
        private ConfigManager configManager2;
        private PropertyManager propertyManager;
        private EnvironmentManager envManager;
        
        // Gestión de utilidades
        private UtilityManager utilityManager;
        private HelperManager helperManager;
        private ToolManager toolManager;
        
        // Constructor que inicializa todo
        public GodClass() {
            // Inicializar todos los managers y servicios
            initializeAllManagers();
        }
        
        private void initializeAllManagers() {
            // Inicialización de todos los managers...
            // (código muy largo omitido por brevedad)
        }
        
        // Métodos que hacen demasiadas cosas
        public void processEverything() {
            // Procesa usuarios, productos, pedidos, pagos, inventario, etc.
        }
        
        public void manageAllData() {
            // Maneja todos los tipos de datos
        }
        
        public void handleAllEvents() {
            // Maneja todos los eventos
        }
        
        public void controlEverything() {
            // Controla todo el sistema
        }
    }
    
    // CODE SMELL: Duplicate Code
    // Código duplicado en múltiples lugares
    public class DuplicateCodeExample {
        
        // Método duplicado en múltiples clases
        public void validateEmail(String email) {
            if (email == null || email.isEmpty()) {
                System.out.println("Email is required");
                return;
            }
            
            if (!email.contains("@")) {
                System.out.println("Invalid email format");
                return;
            }
            
            if (email.length() < 5) {
                System.out.println("Email too short");
                return;
            }
            
            System.out.println("Email is valid");
        }
        
        // Mismo método duplicado
        public void checkEmail(String email) {
            if (email == null || email.isEmpty()) {
                System.out.println("Email is required");
                return;
            }
            
            if (!email.contains("@")) {
                System.out.println("Invalid email format");
                return;
            }
            
            if (email.length() < 5) {
                System.out.println("Email too short");
                return;
            }
            
            System.out.println("Email is valid");
        }
        
        // Mismo método duplicado otra vez
        public void verifyEmail(String email) {
            if (email == null || email.isEmpty()) {
                System.out.println("Email is required");
                return;
            }
            
            if (!email.contains("@")) {
                System.out.println("Invalid email format");
                return;
            }
            
            if (email.length() < 5) {
                System.out.println("Email too short");
                return;
            }
            
            System.out.println("Email is valid");
        }
    }
    
    // CODE SMELL: Primitive Obsession
    // Uso excesivo de tipos primitivos en lugar de objetos
    public class PrimitiveObsessionExample {
        
        // Debería usar objetos en lugar de primitivos
        public void processUserData(String name, String email, String phone, 
                                  String address, String city, String state, 
                                  String zip, String country) {
            // Lógica de procesamiento
        }
        
        // Debería usar objetos para fechas
        public void scheduleMeeting(int year, int month, int day, 
                                  int hour, int minute, int second) {
            // Lógica de programación
        }
        
        // Debería usar objetos para coordenadas
        public void calculateDistance(double lat1, double lon1, 
                                   double lat2, double lon2) {
            // Cálculo de distancia
        }
        
        // Debería usar objetos para dinero
        public void processPayment(double amount, String currency) {
            // Procesamiento de pago
        }
    }
    
    // CODE SMELL: Data Clumps
    // Grupos de datos que siempre van juntos
    public class DataClumpsExample {
        
        // Los parámetros name, email, phone siempre van juntos
        public void createUser(String name, String email, String phone) {
            // Lógica
        }
        
        public void updateUser(String name, String email, String phone) {
            // Lógica
        }
        
        public void deleteUser(String name, String email, String phone) {
            // Lógica
        }
        
        public void validateUser(String name, String email, String phone) {
            // Lógica
        }
        
        public void notifyUser(String name, String email, String phone) {
            // Lógica
        }
    }
    
    // CODE SMELL: Switch Statements
    // Uso excesivo de switch statements
    public class SwitchStatementsExample {
        
        public void processPayment(String paymentType, double amount) {
            switch (paymentType) {
                case "credit":
                    processCreditCard(amount);
                    break;
                case "debit":
                    processDebitCard(amount);
                    break;
                case "paypal":
                    processPayPal(amount);
                    break;
                case "bitcoin":
                    processBitcoin(amount);
                    break;
                case "bank_transfer":
                    processBankTransfer(amount);
                    break;
                case "check":
                    processCheck(amount);
                    break;
                case "cash":
                    processCash(amount);
                    break;
                case "gift_card":
                    processGiftCard(amount);
                    break;
                case "loyalty_points":
                    processLoyaltyPoints(amount);
                    break;
                case "cryptocurrency":
                    processCryptocurrency(amount);
                    break;
                default:
                    throw new IllegalArgumentException("Unknown payment type");
            }
        }
        
        private void processCreditCard(double amount) {
            System.out.println("Processing credit card: " + amount);
        }
        
        private void processDebitCard(double amount) {
            System.out.println("Processing debit card: " + amount);
        }
        
        private void processPayPal(double amount) {
            System.out.println("Processing PayPal: " + amount);
        }
        
        private void processBitcoin(double amount) {
            System.out.println("Processing Bitcoin: " + amount);
        }
        
        private void processBankTransfer(double amount) {
            System.out.println("Processing bank transfer: " + amount);
        }
        
        private void processCheck(double amount) {
            System.out.println("Processing check: " + amount);
        }
        
        private void processCash(double amount) {
            System.out.println("Processing cash: " + amount);
        }
        
        private void processGiftCard(double amount) {
            System.out.println("Processing gift card: " + amount);
        }
        
        private void processLoyaltyPoints(double amount) {
            System.out.println("Processing loyalty points: " + amount);
        }
        
        private void processCryptocurrency(double amount) {
            System.out.println("Processing cryptocurrency: " + amount);
        }
    }
    
    // Clases auxiliares
    public class User {
        private String name, email, phone, address, city, state, zip, country;
        private String company, position, department, manager, salary, hireDate, status;
        private boolean active, admin, verified;
        private List<String> skills;
        private Map<String, Object> preferences;
        private String notes, emergencyContact, emergencyPhone;
        
        // Getters y setters
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }
        public String getPhone() { return phone; }
        public void setPhone(String phone) { this.phone = phone; }
        public String getAddress() { return address; }
        public void setAddress(String address) { this.address = address; }
        public String getCity() { return city; }
        public void setCity(String city) { this.city = city; }
        public String getState() { return state; }
        public void setState(String state) { this.state = state; }
        public String getZip() { return zip; }
        public void setZip(String zip) { this.zip = zip; }
        public String getCountry() { return country; }
        public void setCountry(String country) { this.country = country; }
        public String getCompany() { return company; }
        public void setCompany(String company) { this.company = company; }
        public String getPosition() { return position; }
        public void setPosition(String position) { this.position = position; }
        public String getDepartment() { return department; }
        public void setDepartment(String department) { this.department = department; }
        public String getManager() { return manager; }
        public void setManager(String manager) { this.manager = manager; }
        public String getSalary() { return salary; }
        public void setSalary(String salary) { this.salary = salary; }
        public String getHireDate() { return hireDate; }
        public void setHireDate(String hireDate) { this.hireDate = hireDate; }
        public String getStatus() { return status; }
        public void setStatus(String status) { this.status = status; }
        public boolean isActive() { return active; }
        public void setActive(boolean active) { this.active = active; }
        public boolean isAdmin() { return admin; }
        public void setAdmin(boolean admin) { this.admin = admin; }
        public boolean isVerified() { return verified; }
        public void setVerified(boolean verified) { this.verified = verified; }
        public List<String> getSkills() { return skills; }
        public void setSkills(List<String> skills) { this.skills = skills; }
        public Map<String, Object> getPreferences() { return preferences; }
        public void setPreferences(Map<String, Object> preferences) { this.preferences = preferences; }
        public String getNotes() { return notes; }
        public void setNotes(String notes) { this.notes = notes; }
        public String getEmergencyContact() { return emergencyContact; }
        public void setEmergencyContact(String emergencyContact) { this.emergencyContact = emergencyContact; }
        public String getEmergencyPhone() { return emergencyPhone; }
        public void setEmergencyPhone(String emergencyPhone) { this.emergencyPhone = emergencyPhone; }
    }
    
    // Clases de servicios (simuladas)
    public class DatabaseManager {
        public boolean saveUser(User user) { return true; }
    }
    
    public class EmailService {
        public boolean sendWelcomeEmail(String email) { return true; }
    }
    
    public class FileManager {
        public boolean createUserBackup(User user) { return true; }
    }
    
    public class Logger {
        public void log(String message) { System.out.println("[LOG] " + message); }
    }
    
    public class NotificationService {
        public void notifyAdmin(String message) { System.out.println("Admin notified: " + message); }
    }
    
    public class StatisticsManager {
        public void incrementUserCount() { System.out.println("User count incremented"); }
    }
    
    public class SecurityManager {
        public void validateUser(User user) { System.out.println("User validated: " + user.getName()); }
    }
    
    public class CacheManager {
        public void cacheUser(User user) { System.out.println("User cached: " + user.getName()); }
    }
    
    public class ReportGenerator {
        public void generateUserReport(User user) { System.out.println("Report generated for: " + user.getName()); }
    }
    
    // Clases para GodClass (simuladas)
    public class Product { }
    public class Order { }
    public class Payment { }
    public class Inventory { }
    public class UserDAO { }
    public class ProductDAO { }
    public class OrderDAO { }
    public class PaymentDAO { }
    public class InventoryDAO { }
    public class UserValidator { }
    public class ProductValidator { }
    public class OrderValidator { }
    public class PaymentValidator { }
    public class InventoryValidator { }
    public class UserNotifier { }
    public class ProductNotifier { }
    public class OrderNotifier { }
    public class PaymentNotifier { }
    public class InventoryNotifier { }
    public class ReportExporter { }
    public class ReportScheduler { }
    public class ConfigurationManager { }
    public class SettingsManager { }
    public class PreferencesManager { }
    public class AuthenticationService { }
    public class AuthorizationService { }
    public class AuditTrail { }
    public class ErrorHandler { }
    public class CacheValidator { }
    public class CacheCleaner { }
    public class SMSService { }
    public class BackupManager { }
    public class ArchiveManager { }
    public class NetworkManager { }
    public class APIManager { }
    public class WebSocketManager { }
    public class ConnectionPool { }
    public class TransactionManager { }
    public class MetricsCollector { }
    public class PerformanceMonitor { }
    public class ErrorManager { }
    public class ExceptionHandler { }
    public class RecoveryManager { }
    public class ValidationManager { }
    public class DataValidator { }
    public class BusinessRuleValidator { }
    public class TransformationManager { }
    public class DataTransformer { }
    public class FormatConverter { }
    public class SyncManager { }
    public class DataSynchronizer { }
    public class StateManager { }
    public class EventManager { }
    public class EventDispatcher { }
    public class EventListener { }
    public class TaskManager { }
    public class JobScheduler { }
    public class WorkflowManager { }
    public class ResourceManager { }
    public class MemoryManager { }
    public class ThreadManager { }
    public class TimeManager { }
    public class Scheduler { }
    public class TimerManager { }
    public class CommunicationManager { }
    public class MessageQueue { }
    public class ChannelManager { }
    public class SessionManager { }
    public class ContextManager { }
    public class ConfigManager { }
    public class PropertyManager { }
    public class EnvironmentManager { }
    public class UtilityManager { }
    public class HelperManager { }
    public class ToolManager { }
} 