// Generated by AI on 2024-01-15 using GPT-4

import java.util.*;
import java.io.*;

/**
 * Clase que viola específicamente los principios SOLID
 * para probar el sistema de revisión de IA
 */
public class SolidViolations {
    
    // VIOLACIÓN: Single Responsibility Principle (SRP)
    // Esta clase hace demasiadas cosas: maneja usuarios, emails, base de datos, logging, etc.
    public class UserManager {
        private List<User> users;
        private DatabaseConnection db;
        private EmailService email;
        private Logger logger;
        private FileManager fileManager;
        private SecurityManager security;
        
        public UserManager() {
            this.users = new ArrayList<>();
            this.db = new DatabaseConnection();
            this.email = new EmailService();
            this.logger = new Logger();
            this.fileManager = new FileManager();
            this.security = new SecurityManager();
        }
        
        // Método que viola SRP - hace demasiadas cosas
        public void createUser(String name, String email, String password) {
            // Validación
            if (name == null || email == null || password == null) {
                logger.log("Invalid user data");
                return;
            }
            
            // Crear usuario
            User user = new User(name, email, password);
            users.add(user);
            
            // Guardar en base de datos
            db.saveUser(user);
            
            // Enviar email de bienvenida
            email.sendWelcomeEmail(user.getEmail());
            
            // Guardar en archivo de backup
            fileManager.saveUserBackup(user);
            
            // Logging
            logger.log("User created: " + user.getName());
            
            // Verificación de seguridad
            security.validateUser(user);
            
            // Notificación
            System.out.println("User created successfully");
        }
        
        // Más métodos que violan SRP...
        public void deleteUser(int userId) {
            // Lógica de eliminación + email + logging + backup + seguridad
        }
        
        public void updateUser(int userId, String newName) {
            // Lógica de actualización + email + logging + backup + seguridad
        }
    }
    
    // VIOLACIÓN: Open/Closed Principle (OCP)
    // La clase no está abierta para extensión, cerrada para modificación
    public class PaymentProcessor {
        public void processPayment(String paymentType, double amount) {
            if (paymentType.equals("credit")) {
                // Lógica específica para tarjeta de crédito
                System.out.println("Processing credit card payment: " + amount);
            } else if (paymentType.equals("debit")) {
                // Lógica específica para tarjeta de débito
                System.out.println("Processing debit card payment: " + amount);
            } else if (paymentType.equals("paypal")) {
                // Lógica específica para PayPal
                System.out.println("Processing PayPal payment: " + amount);
            } else if (paymentType.equals("bitcoin")) {
                // Lógica específica para Bitcoin
                System.out.println("Processing Bitcoin payment: " + amount);
            }
            // Si queremos agregar un nuevo método de pago, tenemos que modificar esta clase
        }
    }
    
    // VIOLACIÓN: Liskov Substitution Principle (LSP)
    // Las subclases no pueden sustituir a la clase base
    public class Bird {
        public void fly() {
            System.out.println("Flying...");
        }
        
        public void eat() {
            System.out.println("Eating...");
        }
    }
    
    public class Penguin extends Bird {
        @Override
        public void fly() {
            // Los pingüinos no pueden volar, pero heredan el método
            throw new UnsupportedOperationException("Penguins cannot fly!");
        }
    }
    
    // VIOLACIÓN: Interface Segregation Principle (ISP)
    // Interface que fuerza a implementar métodos innecesarios
    public interface Worker {
        void work();
        void eat();
        void sleep();
        void getSalary();
        void takeVacation();
        void getPromotion();
        void getFired();
        void getMarried();
        void haveChildren();
        void buyHouse();
        void retire();
    }
    
    // Clase que implementa métodos que no necesita
    public class Robot implements Worker {
        @Override
        public void work() {
            System.out.println("Robot working...");
        }
        
        @Override
        public void eat() {
            // Los robots no comen, pero tienen que implementar este método
            throw new UnsupportedOperationException("Robots don't eat!");
        }
        
        @Override
        public void sleep() {
            // Los robots no duermen, pero tienen que implementar este método
            throw new UnsupportedOperationException("Robots don't sleep!");
        }
        
        @Override
        public void getSalary() {
            // Los robots no reciben salario
            throw new UnsupportedOperationException("Robots don't get salary!");
        }
        
        @Override
        public void takeVacation() {
            // Los robots no toman vacaciones
            throw new UnsupportedOperationException("Robots don't take vacations!");
        }
        
        @Override
        public void getPromotion() {
            // Los robots no reciben promociones
            throw new UnsupportedOperationException("Robots don't get promotions!");
        }
        
        @Override
        public void getFired() {
            // Los robots no son despedidos
            throw new UnsupportedOperationException("Robots don't get fired!");
        }
        
        @Override
        public void getMarried() {
            // Los robots no se casan
            throw new UnsupportedOperationException("Robots don't get married!");
        }
        
        @Override
        public void haveChildren() {
            // Los robots no tienen hijos
            throw new UnsupportedOperationException("Robots don't have children!");
        }
        
        @Override
        public void buyHouse() {
            // Los robots no compran casas
            throw new UnsupportedOperationException("Robots don't buy houses!");
        }
        
        @Override
        public void retire() {
            // Los robots no se jubilan
            throw new UnsupportedOperationException("Robots don't retire!");
        }
    }
    
    // VIOLACIÓN: Dependency Inversion Principle (DIP)
    // Depende de implementaciones concretas en lugar de abstracciones
    public class ReportGenerator {
        private MySQLDatabase mysqlDb; // Dependencia concreta
        private FileLogger fileLogger; // Dependencia concreta
        private EmailSender emailSender; // Dependencia concreta
        
        public ReportGenerator() {
            this.mysqlDb = new MySQLDatabase();
            this.fileLogger = new FileLogger();
            this.emailSender = new EmailSender();
        }
        
        public void generateReport() {
            // Depende directamente de implementaciones concretas
            String data = mysqlDb.getData();
            fileLogger.log("Report generated");
            emailSender.send("Report ready");
        }
    }
    
    // Clases concretas que violan DIP
    public class MySQLDatabase {
        public String getData() {
            return "Data from MySQL";
        }
    }
    
    public class FileLogger {
        public void log(String message) {
            System.out.println("File log: " + message);
        }
    }
    
    public class EmailSender {
        public void send(String message) {
            System.out.println("Email sent: " + message);
        }
    }
    
    // Clases auxiliares
    public class User {
        private String name;
        private String email;
        private String password;
        
        public User(String name, String email, String password) {
            this.name = name;
            this.email = email;
            this.password = password;
        }
        
        public String getName() { return name; }
        public String getEmail() { return email; }
        public String getPassword() { return password; }
    }
    
    public class DatabaseConnection {
        public void saveUser(User user) {
            System.out.println("Saving user: " + user.getName());
        }
    }
    
    public class EmailService {
        public void sendWelcomeEmail(String email) {
            System.out.println("Welcome email sent to: " + email);
        }
    }
    
    public class Logger {
        public void log(String message) {
            System.out.println("[LOG] " + message);
        }
    }
    
    public class FileManager {
        public void saveUserBackup(User user) {
            System.out.println("User backup saved: " + user.getName());
        }
    }
    
    public class SecurityManager {
        public void validateUser(User user) {
            System.out.println("Validating user: " + user.getName());
        }
    }

    public class VeryVeryBadCode {
        public void veryVeryBadCode() {
            System.out.println("This is very very bad code");
        }
        int a = 1;
        int b = 2;
        int c = 3;
        int d = 4;
        int e = 5;
        int f = 6;
        int g = 7;
        int h = 8;
        for (int i = 0; i < 10; i++) {
            System.out.println("This is very very bad code");
        }
        while (true) {
            System.out.println("This is very very bad code");
        }
        do {
            System.out.println("This is very very bad code");
        }
        if (a > b) {
            System.out.println("This is very very bad code");
        }
        else {
            System.out.println("This is very very bad code");
        }
        switch (a) {
            case 1:
                System.out.println("This is very very bad code");
                break;
            case 2:
                System.out.println("This is very very bad code");
                break;
        }
    }
} 