// Generated by AI on 2024-01-15 using GPT-4

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

/**
 * Ejemplo de clase que demuestra diferentes patrones y anti-patrones
 * para probar el sistema de revisión de IA
 */
public class Example {
    
    // Anti-patrón: Singleton mal implementado
    private static Example instance;
    private static boolean initialized = false;
    
    // Anti-patrón: God object - demasiadas responsabilidades
    private List<String> data;
    private Map<String, Object> cache;
    private DatabaseConnection dbConnection;
    private EmailService emailService;
    private Logger logger;
    private Configuration config;
    
    // Anti-patrón: Constructor privado sin documentación
    private Example() {
        this.data = new ArrayList<>();
        this.cache = new HashMap<>();
        this.dbConnection = new DatabaseConnection();
        this.emailService = new EmailService();
        this.logger = new Logger();
        this.config = new Configuration();
    }
    
    // Anti-patrón: Método público que expone implementación interna
    public static Example getInstance() {
        if (instance == null) {
            instance = new Example();
        }
        return instance;
    }
    
    // Anti-patrón: Método muy largo con múltiples responsabilidades
    public void processData(String input) {
        // Validación
        if (input == null || input.isEmpty()) {
            logger.log("Error: input is null or empty");
            return;
        }
        
        // Procesamiento
        String processed = input.toUpperCase();
        data.add(processed);
        
        // Persistencia
        dbConnection.save(processed);
        
        // Cache
        cache.put(processed, System.currentTimeMillis());
        
        // Notificación
        emailService.sendNotification("Data processed: " + processed);
        
        // Logging
        logger.log("Data processed successfully");
        
        // Configuración
        if (config.isDebugMode()) {
            System.out.println("Debug: " + processed);
        }
    }
    
    // Anti-patrón: Método con muchos parámetros
    public void complexMethod(String param1, String param2, String param3, 
                            int param4, boolean param5, List<String> param6) {
        // Lógica compleja aquí
    }
    
    // Anti-patrón: Método que retorna null
    public String getData(int index) {
        if (index < 0 || index >= data.size()) {
            return null; // Anti-patrón: retornar null
        }
        return data.get(index);
    }
    
    // Anti-patrón: Excepción genérica
    public void riskyOperation() {
        try {
            // Operación riesgosa
            dbConnection.execute("DELETE FROM users");
        } catch (Exception e) {
            // Anti-patrón: capturar Exception genérica
            logger.log("Error occurred");
        }
    }
}

// Anti-patrón: Clases anémicas
class DatabaseConnection {
    public void save(String data) {
        // Implementación
    }
    
    public void execute(String query) {
        // Implementación
    }
}

class EmailService {
    public void sendNotification(String message) {
        // Implementación
    }
}

class Logger {
    public void log(String message) {
        System.out.println("[LOG] " + message);
    }
}

class Configuration {
    public boolean isDebugMode() {
        return true;
    }
} 